lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Some of the newer beaker-hosgenerator definitions contain underscores
which are illegal as hostnames, preventing vagrant configuring and
bringing up a machine (e.g. windows2012r2_ja-64-1). vmpooler for example
doesn't have a problem with this as the the actual hostname is obtained
from the vmpooler API, whereas beaker-vagrant re-uses the hostname
directly.
Translate any underscores in host.name to hyphens to ensure a legal
hostname.
=> (BKR-1264) Ensure vm.hostname is legal

docs/vagrant.md
I found there was no documentation on volume support in vagrant. I've added a brief explanation and an example config.
=> Improve documentation on volumes support

docs/vagrant.md, lib/beaker/hypervisor/vagrant_virtualbox.rb, spec/beaker/hypervisor/vagrant_virtualbox_spec.rb
You might have to bare with me on this one! 
This PR adds support for changing the type of storage controller that is added by beaker-vagrant when using the "volumes" support. This is necessary because not all vagrant boxes support IntelAHCI (the type that beaker-vagrant was using). 
This PR adds support for LSILogic, PIIX, USB and retains the existing support for IntelAHCI. If you select USB as the controller type, it also ensures that USB is enabled on the VM (without enabling EHCI or XHCI, both of which may require a license from Oracle for the extension pack if you use them).
It also adds some unit tests for volumes support. I'd love to add some integration tests for this too, but that started to blow my mind, and there are currently none for "volumes" anyway.
=> Add support for alternate volume storage controllers

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
FreeBSD needs the MAC address of the VM in the Vagrantfile. Upstream
issue is https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=201904
Beaker issue is https://tickets.puppetlabs.com/browse/BKR-1237
=> (BKR-1237)set vm.base_mac for freebsd in Vagrantfile

lib/beaker/hypervisor/vagrant.rb, lib/beaker/hypervisor/vagrant/mount_folder.rb, spec/beaker/hypervisor/vagrant_spec.rb
Fixing issue with user given invalid keys for synced folders for ex.: copy-paste from docker nodeset.
=> Bugfix: Issue with user given invalid keys for synced folders

acceptance/config/nodes/redhat-nodes.yml, beaker-vagrant.gemspec, docs/vagrant.md
Puppet Labs Vagrant Boxes (https://vagrantcloud.com/puppetlabs/) are unsupported and badly outdated. Due to CentOS lack of TLSv1.2 support, they're also broken for acceptance testing. Since we don't need a Puppet environment preconfigured, I've updated the acceptance nodes to use the official CentOS 7 Vagrant Box. All tests pass.
=> (MAINT) Upgrade acceptance tests and docs

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Similar to setting RUBYLIB to an empty string for BKR-511 my Fedora 28 machine also needs RUBYOPT set to an empty string to avoid bundler issues.
=> Set RUBYOPT to an empty string for bundler

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Commit 8bcb1f8dafd overrides the configure method but this removes a number of important bootstrapping steps like enabling environment variables in the ssh session (for example, add_env_var stopped working because `PermitUserEnvironment` is no longer added to sshd_config).
=> Call configure method of parent class.

lib/beaker/hypervisor/vagrant_virtualbox.rb, spec/beaker/hypervisor/vagrant_virtualbox_spec.rb
Some circumstances (not identified) cause Beaker runs to stop with following error message : 
```
daneel:/tmp/puppet-virtualbox$ RBENV_VERSION=2.5.1 BEAKER_IS_PE=no PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=yes bundle exec rake beaker:ubuntu-server-1804-x64
[... 8x ...]
Hypervisor for ubuntu-server-1804-x64 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create
created Vagrantfile for VagrantHost ubuntu-server-1804-x64
Bringing machine 'ubuntu-server-1804-x64' up with 'virtualbox' provider...
==> ubuntu-server-1804-x64: Importing base box 'ubuntu/bionic64'...
Progress: 10%Progress: 90%==> ubuntu-server-1804-x64: Matching MAC address for NAT networking...
==> ubuntu-server-1804-x64: Checking if box 'ubuntu/bionic64' is up to date...
==> …
```
=> remove audio of SUT with virtualbox

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Beaker relies on setting the environment via ~/.ssh/environment. By using this helper we ensure the path is set correctly and we can execute puppet.
=> (BKR-1553) Set PermitUserEnvironment

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Without this change vagrant is trying to SSH to Windows:
```
==> windows-server-amd64: Waiting for machine to boot. This may take a few minutes...
windows-server-amd64: SSH address: 127.0.0.1:2200
windows-server-amd64: SSH username: vagrant
windows-server-amd64: SSH auth method: private key
```
After this change
```
==> windows-server-amd64: Waiting for machine to boot. This may take a few minutes...
windows-server-amd64: WinRM address: 127.0.0.1:5985
windows-server-amd64: WinRM username: vagrant
windows-server-amd64: WinRM execution_time_limit: PT2H
windows-server-amd64: WinRM transport: negotiate
==> windows-server-amd64: Machine booted and ready!
```
=> Use winrm communicator for Windows

lib/beaker/hypervisor/vagrant_libvirt.rb
Fedora 30 started to default to the session, but the way beaker-vagrant sets up networking is incompatible. Setting up private networks QEMU requires root privileges.
https://github.com/vagrant-libvirt/vagrant-libvirt#qemu-session-support
Note that it's not possible to set this via options because those are always written as strings.
=> Never use QEMU session with libvirt

lib/beaker/hypervisor/vagrant.rb
The error message needed to be converted to a String prior to matching
otherwise the logic was ineffective.
=> Fix WinRM error message matching

.travis.yml, docs/vagrant.md, lib/beaker/hypervisor/vagrant_virtualbox.rb, spec/beaker/hypervisor/vagrant_virtualbox_spec.rb
Before this patch, the (undocumented) Virtualbox host setting `natdns` would break Vagrant by adding the settings 'natdnshostresolver1' and 'natdnsproxy1' with the invalid value `"true"`, regardless of the text 'natdns' was set to for that host.  The valid value Virtualbox expects for these settings is `"on"`: https://www.virtualbox.org/manual/ch09.html#nat-adv-dns .
This patch fixes the issue by:
* Setting `natdnshostresolver1` and `natdnsproxy1` to "on" instead of "true".
* Adding spec tests for `natdns` 
* Documenting `natdns` in docs/vagrant.md
The patch also includes several other minor improvements:
* Adds hyperlinked TOC to docs/vagrant.md and fixes a typo
* Reduces noisy quote-escape syntax by using single-quotes in the Vagrantfile
* Fixes broken syntax in cpuidset for osx …
=> (BKR-1635) Fix and document `natdns`

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Allow SSH settings from nodesets to propagate properly into the host's
SSH configuration.
BKR-1423 #close
=> (BKR-1423) Fix SSH settings in nodesets

.rspec, lib/beaker/hypervisor/vagrant.rb, lib/beaker/hypervisor/vagrant_libvirt.rb, spec/beaker/hypervisor/vagrant_spec.rb
Previously, if any two test runs occurred where the systems had identical
hostnames, then one of the runs would fail indicating that there was a
domain conflict.
This patch ensures that a unique name is created for each run when using
the `libvirt` provider.
Additionally, the string `beaker_` is prepended to the path name so that
it is easier to find your systems when large numbers of VMs are running
at the same time.
It also chooses a different base network when using `libvirt` vs
anything else so that users can use both VirtualBox and `libvirt`
simultaneously.
=> Fix simultaneous runs with the libvirt hypervisor

lib/beaker/hypervisor/vagrant.rb, lib/beaker/hypervisor/vagrant_custom.rb, spec/beaker/hypervisor/vagrant_spec.rb
It's a good practice to only create something if you're going to use it. This also makes it easier to unit test individual components of the hypervisor.
=> Lazily create the vagrant path

lib/beaker/hypervisor/vagrant_libvirt.rb
In b162e77b2f8c8f465a6267385c5a7d3f1a2d2bda the path was updated to make the path unique. However, it's done in the provisioning step. That's the wrong time. If `BEAKER_provision=no` is passed, no provisioning happens and the path is incorrect. By overriding the initializer, it always happens.
Fixes: b162e77b2f8c8f465a6267385c5a7d3f1a2d2bda
=> Correctly override the Vagrant path

lib/beaker/hypervisor/vagrant.rb
In this case `File.basename(__FILE__)` returns `vagrant`. Then the next part is `..` which cancels out the first part thanks to `File.expand_path`.
=> Remove redundant path in path construction

lib/beaker/hypervisor/vagrant.rb, lib/beaker/hypervisor/vagrant_libvirt.rb, spec/beaker/hypervisor/vagrant_desktop_spec.rb, spec/beaker/hypervisor/vagrant_fusion_spec.rb, spec/beaker/hypervisor/vagrant_libvirt_spec.rb, spec/beaker/hypervisor/vagrant_parallels_spec.rb, spec/beaker/hypervisor/vagrant_virtualbox_spec.rb, spec/beaker/hypervisor/vagrant_workstation_spec.rb
Vagrant already has management network by default. Also using a private network creates 2 networks and that often creates routing issues between the host and the guest. This implementation makes the private network generator optional if no IP is set. This keeps it backwards compatible.
=> Stop using private networks on libvirt

lib/beaker/hypervisor/vagrant_libvirt.rb, spec/beaker/hypervisor/vagrant_libvirt_spec.rb
The previous change broke the proper update of /etc/hosts by beaker
which, in turn, broke multi-node testing.
Fixes: #49
=> Remove set_host_default from vagrant_libvirt

.github/workflows/test.yml
also contains https://github.com/voxpupuli/beaker-vagrant/pull/55
=> apply best-practices to GitHub workflow

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
After updating to Fedora 38 (which includes Ruby 3.2 and Bundler 2.4) I started to need this. Perhaps it's also a bug in the system wide vagrant installation to not prune it, but Bundler provides a way to run with all bundler-related variables removed. Since there was already some code to try this, it now goes the whole way.
=> Use Bundler to clean the environment

beaker-vagrant.gemspec
Since aae8cea0f60b03077d2283a356ff89a285c3b134 the gem no longer depends on the RuboCop config from Beaker, so version 4 works again.
=> Allow beaker 4 again

lib/beaker/hypervisor/vagrant.rb
When the Beaker setfile doesn't exist, Beaker calls beaker-hostgenerator and sets the :hosts_file_generated option. These directory names can become very long and in some cases exceed some limits when used with vagrant-libvirt.
This only uses the hostnames and discards all options passed. This can break some scenarios where a host is reused and a user may assume that passing in new options changes the host.
Currently a draft to test if it resolves the `Call to virDomainCreateWithFlags failed: Invalid machine name` error reported in https://github.com/voxpupuli/gha-puppet/pull/49#issuecomment-1906247620
=> Use shorter directory names for beaker-hostgenerator

Gemfile
It's an optional dependency of GCG and we get warnings if it's missing. We added it to other repos as well.
=> Gemfile: add faraday as GCG dependency
